#!/bin/sh
#
# An example hook script to verify what is about to be committed.
# Called by "git commit" with no arguments.  The hook should
# exit with non-zero status after issuing an appropriate message if
# it wants to stop the commit.
#
# To enable this hook, rename this file to "pre-commit".

# Ensure a proper user email is configured
email=$(git config user.email)
if [[ ( -z "$email" ) || ( "$email" =~ FIXME ) ]]
then
	cat <<EOF
Error: You have not specified a proper email address. Current email is "$email".

Please run \`git config [--global] user.email <your_email>\` to supply a value.
EOF
	exit 1
fi
