#!/bin/sh
#
# Git hook that verifies the user has set a proper email address in his or her
# gitconfig, otherwise exits with an error (aborting the commit).

email=$(git config user.email)
if [[ ( -z "$email" ) || ( "$email" =~ FIXME ) ]]
then
    cat <<EOF
Error: You have not specified a proper email address. Current email is "$email".

Please run \`git config [--global] user.email <your_email>\` to supply a value.
EOF
    exit 1
fi
