#!/bin/sh
#
# Copy this file in your home directory with the name ".zshlocalrc" and add
# local machine configurations for zsh here. It will be sourced automatically
# when using this project's zshrc.
#
# If your configuration includes commands that you only want to run the first
# time ZSH is sourced, you can call the is_first_source function. An example
# follows.
#
# alias foo='fortune | cowsay | lolcat'
# export JAVA_HOME=/path/to/java/bins
# export ANDROID_HOME=/path/to/android/sdk
#
# # Avoid adding PATH components on every source.
# if [[ is_first_source ]]; then
#     append_path "$JAVA_HOME" "ANDROID_HOME"
# fi
