#!/bin/sh

# Uncomment if you are not using the launch agent to set them
# (see android.setenv.plist)
# export JAVA7_HOME=$(/usr/libexec/java_home -v1.7)
# export JAVA8_HOME=$(/usr/libexec/java_home -v1.8)
# export JAVA9_HOME=$(/usr/libexec/java_home -v1.9)
# export JAVA_HOME=$JAVA8_HOME
alias java7='export JAVA_HOME=$JAVA7_HOME'
alias java8='export JAVA_HOME=$JAVA8_HOME'
alias java9='export JAVA_HOME=$JAVA9_HOME'

# export ANDROID_HOME="${HOME}/android-sdk-macosx"
